# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'neXjob.in' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'IQKeyboardManagerSwift'
pod 'SideMenu'
pod 'Alamofire'
pod 'Kingfisher'
pod 'SwiftyJSON'
pod 'DropDown'
pod 'razorpay-pod', '1.2.5'
  # Pods for neXjob.in

  target 'neXjob.inTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'neXjob.inUITests' do
    # Pods for testing
  end

end
